# Generated by Django 2.2 on 2020-04-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitwise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amount_messages_user_to_user',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
