# Generated by Django 2.2 on 2020-09-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitwise', '0002_auto_20200420_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='group_members_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('count_of_users', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='user_to_user_mapping',
            old_name='user_to_user',
            new_name='user1',
        ),
        migrations.RemoveField(
            model_name='users_to_group_mapping',
            name='count_of_users',
        ),
        migrations.RemoveField(
            model_name='users_to_group_mapping',
            name='group_members',
        ),
        migrations.AddField(
            model_name='user_to_user_mapping',
            name='user2',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users_to_group_mapping',
            name='user',
            field=models.CharField(default='temp', max_length=100),
            preserve_default=False,
        ),
    ]
