# Generated by Django 2.2 on 2020-09-04 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splitwise', '0003_auto_20200904_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users_to_group_mapping',
            old_name='user',
            new_name='user_name',
        ),
    ]
