# Generated by Django 2.2 on 2020-09-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitwise', '0004_auto_20200904_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='group_name_group_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='amount_messages_users_to_group',
            name='group_name',
        ),
        migrations.RemoveField(
            model_name='group_members_count',
            name='group_name',
        ),
        migrations.RemoveField(
            model_name='users_to_group_mapping',
            name='group_name',
        ),
        migrations.RemoveField(
            model_name='users_to_group_mapping',
            name='user_name',
        ),
        migrations.AddField(
            model_name='amount_messages_users_to_group',
            name='group_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group_members_count',
            name='group_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users_to_group_mapping',
            name='group_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users_to_group_mapping',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='amount_messages_user_to_user',
            name='receiver',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='amount_messages_user_to_user',
            name='sender',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='amount_messages_users_to_group',
            name='sender',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_to_user_mapping',
            name='user1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_to_user_mapping',
            name='user2',
            field=models.IntegerField(),
        ),
    ]
